[keyboard]
bindings = [
	{ key = "C", mods = "Control|Shift", action = "Copy"},
	{ key = "V", mods = "Control|Shift", action = "Paste"},
	{ key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
	{ key = "M", mods = "Control|Shift", action = "ToggleMaximized" },
	{ key = "F", mods = "Control|Shift", action = "ToggleFullscreen" },
]

[mouse]
hide_when_typing = true
bindings = [
	{ mouse = "Right", mods = "Control", action = "Paste" },
]
