## === basic === ##
# set colors
set -g default-terminal 'tmux-256color'
set -sg terminal-overrides ',*:RGB'
set -gq allow-passthrough on
# windows and panes number
set -g base-index 1			# window base index, which means start from 1
set -g pane-base-index 1	# pane base index
set -g renumber-windows on	# renumber
# enable mouse
set -g mouse on
# enable clipboard
set -g set-clipboard on

## === windows === ##
set -g window-style "bg=#1E1E2E"
set -g window-active-style "bg=#1E1E2E"

## === status bar === ##
set -g status-position bottom
set -g status-bg "#1E1E2E"
set -g status-fg white
set -g @prefix_highlight_show_prefix on
set -g status-left ""
set -g status-right "\
	#[fg=#CBA6F7] %Y-%m-%d |\
	#[fg=#CBA6F7] %H:%M |\
	#{?client_prefix,#[fg=#CBA6F7] [PREFIX] ,#[fg=#876FA5]  PREFIX  }\
"
set -g window-status-current-format "\
	#[bg=#CBA6F7,fg=#313244,bold] #I \
	#[bg=#1E1E2E,fg=#CDD6F4] #W \
"
set -g window-status-format "\
	#[bg=#876FA5,fg=#313244] #I \
	#[bg=#1E1E2E,fg=#A5ADCB] #W \
"

## === keymaps === ##
# prefix
unbind C-b
set -g prefix C-Space
# window
bind . next-window
bind , previous-window
bind n new-window
bind x kill-window
bind y copy-mode
# pane
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind v split-window -v
bind c split-window -h
bind d kill-pane
# yank mode(require wl-clipboard package in wayland)
## normal mode --y--> yank mode -C-v-> select block --y--> yank
## normal mode --y--> yank mode -C-v-> select line --y--> yank
bind -T copy-mode-vi C-v send -X begin-selection
bind -T copy-mode-vi y send -X copy-pipe-and-cancel "wl-copy" # yank to clipboard
