[mgr]
ratio = [2, 3, 4]
show_hidden = true
show_symlink = true
linemode = "size"
scrolloff = 5
## sort
sort_by = "natural"
sort_dir_first = true
sort_sensitive = true
sort_reverse = false
mouse_events = []

[preview]
wrap = "no"
tab_size = 4
max_width = 80
max_height = 50

