# theme
include current-theme.conf

## fonts
# font_family LiterationMonoNF
# bold_font LiterationMonoNF-Bold
# italic_font LiterationMonoNF-Italic
# bold_italic_font LiterationMonoNF-BoldItalic

font_family Liberation Mono
bold_font Liberation Mono Bold
italic_font Liberation Mono Italic
bold_italic_font Liberation Mono Bold Italic

font_size 17.0

## window
hide_window_decorations yes
window_padding_width 5
background_opacity 0.9
remember_window_size yes

## clipboard
confirm_paste no

## cursor
shell_integration no-cursor
